apiVersion: v1
kind: Service
metadata:
  name: kube-dep-guard-webhook
  namespace: kube-dep-guard-system
spec:
  selector:
    app.kubernetes.io/component: webhook
  ports:
    - name: https
      port: 443
      targetPort: https
