apiVersion: v1
kind: Pod
metadata:
  name: enforce-pod-missing-configmap
  annotations:
    dependency.kubedepguard.io/mode: enforce
spec:
  containers:
    - name: app
      image: nginx:stable
      envFrom:
        - configMapRef:
            name: does-not-exist
